### ISSUE TITLE
System.out.println in class

### ISSUE THREAD

**Issue by smillidge** [javaee/hk2#14]
https://github.com/hk2-project/hk2/blob/f51e6319588a28f36501476e58c06df54de4912a/hk2-configuration/persistence/hk2-xml-dom/hk2-config/src/main/java/org/jvnet/hk2/config/ConfigurationPopulator.java

Has a System.out.println in it which should be replaced with a log message.

**Comment by jwells131313** [comment]
Fixed it.

**Comment by smillidge** [comment]
Thank you
