### ISSUE TITLE
where should we get artifact 2.5.0-b37?

### ISSUE THREAD

**Issue by mulderbaba** [javaee/hk2#356]
I guess maven.java.net is not being used for distributions of hk2 so where should we get the latest artifact from?

**Comment by romain-grecourt** [comment]
b37 was dropped.
The current latest build is 2.5.0-b36, you can find it in maven central http://repo1.maven.org/maven2/org/glassfish/hk2/hk2/2.5.0-b36/

**Comment by mulderbaba** [comment]
thanks @romain-grecourt, is that valid for b38 as well?

**Comment by jwells131313** [comment]
We are actually working on the promotion pipe-line right now, so it's 
unclear which version will be the next one lol.

Stay tuned...

**Comment by mulderbaba** [comment]
yup @jwells131313, I am following the details:) any ETA on releasing 2.5.0 then? I want to get it bundled with the next release of Payara.

**Comment by jwells131313** [comment]
You can get the latest build versions at http://search.maven.org/#search%7Cga%7C1%7Chk2

**Comment by mulderbaba** [comment]
thanks @jwells131313, starting w/ b37 release maven is suffering from a possible pom parsing problem and terminating with:

```
[ERROR] GC overhead limit exceeded -> [Help 1]
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:108)
	at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parsePluginExecution(MavenXpp3ReaderEx.java:3347)
```
I will investigate it in detail.

**Comment by jwells131313** [comment]
We don't seem to be having that issue.  All our Hudsons and my personal build is working fine

**Comment by mulderbaba** [comment]
upgrading to maven 3.5.0 solved the problem.
